### ISSUE TITLE
"The system cannot find the path specified" on Windows 10

### ISSUE THREAD

**Issue by mcmxcdev** [simoneb/fast-folder-size#12]
The library works as expected on macOS and Ubuntu, but it doesn't play well with our application on Windows:

```
Uncaught (in promise) Error: Command failed: "C:\Users\Markus\AppData\Local\Programs\ferdi\resources\app.asar\node_modules\fast-folder-size\bin\du.exe" -nobanner -accepteula -q -c .
The system cannot find the path specified.

    at ChildProcess.exithandler (node:child_process:406)
    at ChildProcess.emit (node:events:394)
    at maybeClose (node:internal/child_process:1067)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301)
```

It is an open source electron application, so you can check the source code in case you need more information: https://github.com/getferdi/ferdi

**Comment by RafeSafari** [comment]
I was experiencing the same issue after removing entire `node_modules` directory and re installing all packages via `npm i` command.
But downgrading to previous version (`npm i fast-folder-size@1.4.0`) and upgrading again (`npm i fast-folder-size@1.5.0`) triggered postinstall script and bin files are created and ready to use.

**Comment by simoneb** [comment]
Thanks @RafeSafari , on Windows du.exe is downloaded and installed using the postinstall npm script. It makes sense that re-installing the package may fix a previously broken installation. I'm not sure if there's a more reliable way to do the same.
