### ISSUE TITLE
Error: spawn C:\WINDOWS\system32\cmd.exe ENOENT

### ISSUE THREAD

**Issue by MarvinXu** [simoneb/fast-folder-size#15]
Error in a git bash shell, works in cmd shell

**Comment by simoneb** [comment]
![image](https://user-images.githubusercontent.com/20181/159752836-599e9a7a-a2a8-4df6-a8f9-02bda32795bc.png)

works for me

**Comment by MarvinXu** [comment]
Thanks for the reply! I checked again, works fine in cli or with `require`. This error occurs when use ES imports:
```js
import fastFolderSize from 'fast-folder-size'

fastFolderSize('../dist', (err, bytes) => {
  if (err)
    console.error(err)

  console.log(bytes)
})
```
![image](https://user-images.githubusercontent.com/7382357/159815597-57aa0ba2-27f9-4b50-89d1-5ad22f3db91f.png)

**Comment by simoneb** [comment]
Cannot reproduce. Make sure you're actually pointing it to a path that exists.

```js
// index.mjs
import fastFolderSize from 'fast-folder-size'

fastFolderSize('.', (err, bytes) => {
  if (err)
    console.error(err)

  console.log(bytes)
})
```

![image](https://user-images.githubusercontent.com/20181/159917495-34e64597-3101-4b1c-b3cb-b4fd375c2174.png)

**Comment by MarvinXu** [comment]
Sorry, it is a path problem. So it turns out `.` means the **project root** rather than the current folder of the executing file.
