### ISSUE TITLE
Can't download DU.zip from behind a corporate firewall

### ISSUE THREAD

**Issue by markmclauchlan** [simoneb/fast-folder-size#18]
I can't install this from behind our corporate firewall because all .zip downloads from external sources are blocked. 

Could the location of DU.zip be a configuration option?

Cypress do something similar, they have a CYPRESS_INSTALL_BINARY environment to specify the location - https://github.com/cypress-io/cypress/blob/3c286177cc57e699062162d9db9ba12a562e2ccf/cli/lib/tasks/install.js#L172.

**Comment by simoneb** [comment]
Good idea! Would you like to send a PR to do this?

**Comment by markmclauchlan** [comment]
My javascript isn't the best! I've created a PR for that now anyway

**Comment by markmclauchlan** [comment]
I'll close this now - when are you planning the next publish?

**Comment by mubaidr** [comment]
Is there any possibility to specify local disk address for file?

**Comment by simoneb** [comment]
See the docs

**Comment by mubaidr** [comment]
> See the docs

But as per docs, it only supports using custom web server for `du.zip` delivery. 

Would you be open to add support for local file address, I am willing to create a pull request.

**Comment by asicfr** [comment]
Is there any chance in the futur to not have to download du.zip and use true dependency ?

**Comment by simoneb** [comment]
> Is there any chance in the futur to not have to download du.zip and use true dependency ?

The answer is no because the license explicitly forbids it. See https://learn.microsoft.com/en-us/sysinternals/license-faq#may-i-distribute-sysinternals-utilities-in-my-software--on-my-website--or-with-my-magazine-
