### ISSUE TITLE
Block `Running postinstall script...`

### ISSUE THREAD

**Issue by 171h** [simoneb/fast-folder-size#60]
This package blocked `Running postinstall script...` when use `pnpm` package manager

link [antfu/vitesse-nuxt3/#99](https://github.com/antfu/vitesse-nuxt3/issues/99)
link [antfu/vitesse-nuxt3/#100](https://github.com/antfu/vitesse-nuxt3/pull/100)

### Case 1  [antfu/vitesse-nuxt3](https://github.com/antfu/vitesse-nuxt3)
```
pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +1209
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1209, reused 1205, downloaded 0, added 0, done
node_modules/.pnpm/fast-folder-size@2.1.0/node_modules/fast-folder-size: Running postinstall script...
```

### Case 2 [nuxtlabs/ui](https://github.com/nuxtlabs/ui)
```
pnpm install
Scope: all 2 workspace projects
Packages: +1488
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: g:\.pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1541, reused 1381, downloaded 96, added 1488, done
node_modules/.pnpm/fast-folder-size@2.1.0/node_modules/fast-folder-size: Running postinstall script...
node_modules/.pnpm/vue-demi@0.14.5_vue@3.3.4/node_modules/vue-demi: Running postinstall script, done in 373ms
```

**Comment by simoneb** [comment]
Can you please provide a repro? I tried creating a simple package with this package as a sigle dependency, using pnpm, and everything works fine.

**Comment by 171h** [comment]
You can try the two case repo above please.

**Comment by simoneb** [comment]
That's not how it works, I have tried a minimal repro and it works fine. You can't expect me to debug your repositories. As far as I can tell the issue is in your repo, unless you prove otherwise by putting together a minimal repro.

**Comment by 171h** [comment]
> That's not how it works, I have tried a minimal repro and it works fine. You can't expect me to debug your repositories. As far as I can tell the issue is in your repo, unless you prove otherwise by putting together a minimal repro.

Thanks for your reply, in fact I'm not sure if it's a problem with this package，but if i add 
`"pnpm": {"neverBuiltDependencies":["fast-folder-size"]`to the `package.json`，the block will be disappear. This is also my current solution.

**Comment by simoneb** [comment]
Well that's not really a solution because if the package is being used, preventing it from building will not download the required dependency which will allow the package to work. Try executing the postinstall script of this package in your repo manually, and see what happens.

**Comment by 171h** [comment]
> Well that's not really a solution because if the package is being used, preventing it from building will not download the required dependency which will allow the package to work. Try executing the postinstall script of this package in your repo manually, and see what happens.

I tried, but I couldn't even successfully install this package separately, this may have something to do with my network.

I think this may be a bug of `http.get` of nodejs. I can download `DU.zip` from `https://download.sysinternals.com/files/DU.zip` manually, but  here is a high possibility of download failure using ``http.get` `. Perhaps bundling  `DU.zip` with this package is a foolproof choice, of course, this will increase the size of this package.

**Comment by AvailableForTheWorld** [comment]
the issue still happened for me, I used nuxt3 framwork repo and when I installed it , it failed with : `../../node_modules/.pnpm/fast-folder-size@2.1.0/node_modules/fast-folder-size: Running postinstall script...`

**Comment by simoneb** [comment]
Folks we need a repro, without that not much I can do. If you think the issue is Nuxt, put together a simple Nuxt app with this package installed to show the problem, if it occurs.

**Comment by 171h** [comment]
> Folks we need a repro, without that not much I can do. If you think the issue is Nuxt, put together a simple Nuxt app with this package installed to show the problem, if it occurs.

I don't think who can provide a repo to reproduce the issue, because the issue is related to the developer's network environment, if you have a problem with your network environment, even the simplest `pnpm add post-folder-size` installation command can reproduce the issue, otherwise the issue will not occur anyway. 

However, this problem is not a bug for this package, but this package can indeed avoid this problem by bundling the `DU.zip ` file instead of downloading it  by `postinstall`.

**Comment by simoneb** [comment]
We can't bundle SysInternals DU due to licensing. The work being done in #56 could indeed address this issue by referencing an already-downloaded copy of DU.

**Comment by MangMax** [comment]
> > Folks we need a repro, without that not much I can do. If you think the issue is Nuxt, put together a simple Nuxt app with this package installed to show the problem, if it occurs.
> 
> I don't think who can provide a repo to reproduce the issue, because the issue is related to the developer's network environment, if you have a problem with your network environment, even the simplest `pnpm add post-folder-size` installation command can reproduce the issue, otherwise the issue will not occur anyway.
> 
> However, this problem is not a bug for this package, but this package can indeed avoid this problem by bundling the `DU.zip ` file instead of downloading it by `postinstall`.

May I ask if you can install it normally? I also encountered the same problem while initializing the nuxt3 project, which seems to have not been resolved.

**Comment by TLovers** [comment]
> > Folks we need a repro, without that not much I can do. If you think the issue is Nuxt, put together a simple Nuxt app with this package installed to show the problem, if it occurs.
> 
> I don't think who can provide a repo to reproduce the issue, because the issue is related to the developer's network environment, if you have a problem with your network environment, even the simplest `pnpm add post-folder-size` installation command can reproduce the issue, otherwise the issue will not occur anyway.
> 
> However, this problem is not a bug for this package, but this package can indeed avoid this problem by bundling the `DU.zip ` file instead of downloading it by `postinstall`.

解决了吗？ 这个依赖包在命令行卡了一个多小时了，有解决办法吗

**Comment by TLovers** [comment]
@171h 
解决了吗？ 这个依赖包在命令行卡了一个多小时了，有解决办法吗

**Comment by simoneb** [comment]
> May I ask if you can install it normally? I also encountered the same problem while initializing the nuxt3 project, which seems to have not been resolved.

You can, see the README.

**Comment by MangMax** [comment]
> @171h 解决了吗？ 这个依赖包在命令行卡了一个多小时了，有解决办法吗

我直接在bin下放入du.zip可以了

**Comment by TLovers** [comment]
> > @171h 解决了吗？ 这个依赖包在命令行卡了一个多小时了，有解决办法吗
> 
> 我直接在bin下放入du.zip可以了

那个readme里面的 export，window 下是没有的，我用set命令 还是无效。最后放在项目里，preinstall hook 执行的时候利用cross-env 设置环境变量才解决了...
