### ISSUE TITLE
No TypeScript types in package

### ISSUE THREAD

**Issue by summetdev** [simoneb/fast-folder-size#9]
I downloaded this library using `npm i fast-folder-size@latest` and there's no type declarations.

![image](https://user-images.githubusercontent.com/55251897/125110398-2f473980-e0ed-11eb-8d61-334d6b47ee63.png)

Related: https://github.com/simoneb/fast-folder-size/pull/8

**Comment by simoneb** [comment]
It wasn't published to npm. Now it is, thanks for reporting it!

**Comment by summetdev** [comment]
Thank you for fix, have a nice day.
